import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="h-full" lang="en">
      <body className={inter.className + " grid grid-rows-[auto,1fr,auto] min-h-full overflow-y-scroll"}>
        <Navbar />
        <main className="min-h-[50vh]">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
